In [5]:
import pandas as pd

In [17]:
#DataFrame
df = pd.read_csv('data/data1.csv', index_col='date')
df.head()

,pool_id,cycle,surface(ha),days,week,surviving,density(shrimp),density(shrimp/ha),weight(g),growth,biomass(kg),biomass(kg/ha),food(kg),food(kg/ha),type_feeding,Medicion,Alimento acumulado [Kg],FCA
date,,,,,,,,,,,,,,,,,,
2020-07-01,4,2020,4.9,0,0.000000,1.00,998000.0,203673.469388,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
2020-07-02,4,2020,4.9,1,0.142857,0.98,978040.0,199600.000000,0.15,0.00,146.7060,29.940000,37.5,7.653061224489796,Boleo,NaN,37.5,375.000000
2020-07-03,4,2020,4.9,2,0.285714,0.97,968060.0,197563.265306,0.18,0.03,174.2508,35.561388,40.0,8.16326530612245,Boleo,NaN,77.5,2.803421
2020-07-04,4,2020,4.9,3,0.428571,0.96,958080.0,195526.530612,0.24,0.06,229.9392,46.926367,40.0,8.16326530612245,Boleo,NaN,117.5,1.410002
2020-07-05,4,2020,4.9,4,0.571429,0.95,948100.0,193489.795918,0.30,0.06,284.4300,58.046939,50.0,10.204081632653061,Boleo,NaN,167.5,1.215318

In [20]:
#Filtrado de columna => Serie
filtro1 = df[  ['growth','weight(g)']   ]

In [22]:
df.iloc[[2,3], [8,6]]

            surviving  density(shrimp)
date
2020-07-03       0.97         968060.0
2020-07-04       0.96         958080.0

In [25]:
df.loc[ '2020-07-03','surviving']

0.97

In [39]:
#Filtrado pro condicion
filcon1 = df[ (df['weight(g)']>15) & (df['days']>=70) ]
filcon1.head()

,pool_id,cycle,surface(ha),days,week,surviving,density(shrimp),density(shrimp/ha),weight(g),growth,biomass(kg),biomass(kg/ha),food(kg),food(kg/ha),type_feeding,Medicion,Alimento acumulado [Kg],FCA
date,,,,,,,,,,,,,,,,,,
2020-09-09,4,2020,4.9,70,10.000000,0.810,808380.0,164975.510204,15.6000,0.3000,12610.72800,2573.617959,400.0,81.63265306122449,AA/platos,NaN,16237.5,1.302739
2020-09-10,4,2020,4.9,71,10.142857,0.808,806384.0,164567.959184,15.9000,0.3000,12821.50560,2616.633796,425.0,86.73469387755101,AA/platos,1.0,16662.5,1.314606
2020-09-11,4,2020,4.9,72,10.285714,0.806,804388.0,164160.612245,16.2375,0.3375,13061.25015,2665.561255,450.0,91.83673469387755,AA/platos,NaN,17112.5,1.325046
2020-09-12,4,2020,4.9,73,10.428571,0.804,802392.0,163753.265306,16.5750,0.3375,13299.64740,2714.213755,450.0,91.83673469387755,AA/platos,NaN,17562.5,1.335243
2020-09-13,4,2020,4.9,74,10.571429,0.802,800396.0,163345.918367,16.9125,0.3375,13536.69735,2762.591296,0.0,0,NaN,NaN,17562.5,1.311604

In [41]:
df['su/ha'] = df['surviving']/df['surface(ha)'] *100
df.head()

,pool_id,cycle,surface(ha),days,week,surviving,density(shrimp),density(shrimp/ha),weight(g),growth,biomass(kg),biomass(kg/ha),food(kg),food(kg/ha),type_feeding,Medicion,Alimento acumulado [Kg],FCA,su/ha
date,,,,,,,,,,,,,,,,,,,
2020-07-01,4,2020,4.9,0,0.000000,1.00,998000.0,203673.469388,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,20.408163
2020-07-02,4,2020,4.9,1,0.142857,0.98,978040.0,199600.000000,0.15,0.00,146.7060,29.940000,37.5,7.653061224489796,Boleo,NaN,37.5,375.000000,20.000000
2020-07-03,4,2020,4.9,2,0.285714,0.97,968060.0,197563.265306,0.18,0.03,174.2508,35.561388,40.0,8.16326530612245,Boleo,NaN,77.5,2.803421,19.795918
2020-07-04,4,2020,4.9,3,0.428571,0.96,958080.0,195526.530612,0.24,0.06,229.9392,46.926367,40.0,8.16326530612245,Boleo,NaN,117.5,1.410002,19.591837
2020-07-05,4,2020,4.9,4,0.571429,0.95,948100.0,193489.795918,0.30,0.06,284.4300,58.046939,50.0,10.204081632653061,Boleo,NaN,167.5,1.215318,19.387755

In [42]:
df['surviving'] = df['surviving']*100

In [54]:
#Valore nulos
dfSinNulos = df.dropna()
dfSinNulos

dfLlenadoNulos = df.fillna(1)
dfLlenadoNulos

dfLlenadoNulosporCol = df.fillna({
    'weight(g)': 1,
    'biomass(kg)':0
})

#llenado con vecinos
llenadoVecino = df.fillna(method='ffill')
llenadoVecino.head()

,pool_id,cycle,surface(ha),days,week,surviving,density(shrimp),density(shrimp/ha),weight(g),growth,biomass(kg),biomass(kg/ha),food(kg),food(kg/ha),type_feeding,Medicion,Alimento acumulado [Kg],FCA,su/ha
date,,,,,,,,,,,,,,,,,,,
2020-07-01,4,2020,4.9,0,0.000000,100.0,998000.0,203673.469388,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,20.408163
2020-07-02,4,2020,4.9,1,0.142857,98.0,978040.0,199600.000000,0.15,0.00,146.7060,29.940000,37.5,7.653061224489796,Boleo,NaN,37.5,375.000000,20.000000
2020-07-03,4,2020,4.9,2,0.285714,97.0,968060.0,197563.265306,0.18,0.03,174.2508,35.561388,40.0,8.16326530612245,Boleo,NaN,77.5,2.803421,19.795918
2020-07-04,4,2020,4.9,3,0.428571,96.0,958080.0,195526.530612,0.24,0.06,229.9392,46.926367,40.0,8.16326530612245,Boleo,NaN,117.5,1.410002,19.591837
2020-07-05,4,2020,4.9,4,0.571429,95.0,948100.0,193489.795918,0.30,0.06,284.4300,58.046939,50.0,10.204081632653061,Boleo,NaN,167.5,1.215318,19.387755

In [59]:
dfLlenadoNulos = df.fillna('1')

dfLlenadoNulos[ dfLlenadoNulos['type_feeding']=='Boleo']
dfLlenadoNulos[ dfLlenadoNulos['type_feeding'].str.contains('Boleo') ].head()

,pool_id,cycle,surface(ha),days,week,surviving,density(shrimp),density(shrimp/ha),weight(g),growth,biomass(kg),biomass(kg/ha),food(kg),food(kg/ha),type_feeding,Medicion,Alimento acumulado [Kg],FCA,su/ha
date,,,,,,,,,,,,,,,,,,,
2020-07-02,4,2020,4.9,1,0.142857,98.0,978040.0,199600.000000,0.15,0.00,146.706,29.94,37.5,7.653061224489796,Boleo,1,37.5,375.0,20.000000
2020-07-03,4,2020,4.9,2,0.285714,97.0,968060.0,197563.265306,0.18,0.03,174.2508,35.561388,40.0,8.16326530612245,Boleo,1,77.5,2.803421,19.795918
2020-07-04,4,2020,4.9,3,0.428571,96.0,958080.0,195526.530612,0.24,0.06,229.9392,46.926367,40.0,8.16326530612245,Boleo,1,117.5,1.410002,19.591837
2020-07-05,4,2020,4.9,4,0.571429,95.0,948100.0,193489.795918,0.3,0.06,284.43,58.046939,50.0,10.204081632653061,Boleo,1,167.5,1.215318,19.387755
2020-07-06,4,2020,4.9,5,0.714286,94.0,938120.0,191453.061224,0.37,0.07,347.1044,70.837633,70.0,14.285714285714285,Boleo,1,237.5,1.184548,19.183673

In [66]:
def DaysToWeek(x):
    return x/7

df['week2'] = df['week']/7
df['week3'] = df['week'].apply(DaysToWeek)
df['week4'] = df['week'].apply(lambda x: x/7)

#Crear columnas que me digan que piscinas son buenas
def catPool(x):
    if x<1.5:
        return 'Buena'
    return 'Mala'

df['cat'] = df['FCA'].apply(catPool)
df['cat1'] = df['FCA'].apply(lambda x: 'Buena' if x<1.5 else 'Mala')

df.head()

,pool_id,cycle,surface(ha),days,week,surviving,density(shrimp),density(shrimp/ha),weight(g),growth,...,type_feeding,Medicion,Alimento acumulado [Kg],FCA,su/ha,week2,week3,week4,cat,cat1
date,,,,,,,,,,,,,,,,,,,,,
2020-07-01,4,2020,4.9,0,0.000000,100.0,998000.0,203673.469388,NaN,0.00,...,NaN,NaN,0.0,NaN,20.408163,0.000000,0.000000,0.000000,Mala,Mala
2020-07-02,4,2020,4.9,1,0.142857,98.0,978040.0,199600.000000,0.15,0.00,...,Boleo,NaN,37.5,375.000000,20.000000,0.020408,0.020408,0.020408,Mala,Mala
2020-07-03,4,2020,4.9,2,0.285714,97.0,968060.0,197563.265306,0.18,0.03,...,Boleo,NaN,77.5,2.803421,19.795918,0.040816,0.040816,0.040816,Mala,Mala
2020-07-04,4,2020,4.9,3,0.428571,96.0,958080.0,195526.530612,0.24,0.06,...,Boleo,NaN,117.5,1.410002,19.591837,0.061224,0.061224,0.061224,Buena,Buena
2020-07-05,4,2020,4.9,4,0.571429,95.0,948100.0,193489.795918,0.30,0.06,...,Boleo,NaN,167.5,1.215318,19.387755,0.081633,0.081633,0.081633,Buena,Buena

In [ ]:
#Filtrado con apply
df[ df['FCA'].apply(lambda x: x<1.5) ]
df[ df['FCA']<1.5 ]

In [76]:
#apply con varias columnas
def catPool2(x):
    fca = x['FCA']
    su = x['surviving']
    
    if fca<1.2 and su>50:
        return 'Buena'
    return 'Mala'

df['cat4'] = df[['FCA','surviving']].apply(catPool2, axis=1) #1fila, 0 col
df['cat5'] = df[['FCA','surviving']].apply(lambda x: 'Buena' if x['FCA']<1.2 and x['surviving']>50 else 'Mala', axis=1) 
df.head()

,pool_id,cycle,surface(ha),days,week,surviving,density(shrimp),density(shrimp/ha),weight(g),growth,...,Alimento acumulado [Kg],FCA,su/ha,week2,week3,week4,cat,cat1,cat4,cat5
date,,,,,,,,,,,,,,,,,,,,,
2020-07-01,4,2020,4.9,0,0.000000,100.0,998000.0,203673.469388,NaN,0.00,...,0.0,NaN,20.408163,0.000000,0.000000,0.000000,Mala,Mala,Mala,Mala
2020-07-02,4,2020,4.9,1,0.142857,98.0,978040.0,199600.000000,0.15,0.00,...,37.5,375.000000,20.000000,0.020408,0.020408,0.020408,Mala,Mala,Mala,Mala
2020-07-03,4,2020,4.9,2,0.285714,97.0,968060.0,197563.265306,0.18,0.03,...,77.5,2.803421,19.795918,0.040816,0.040816,0.040816,Mala,Mala,Mala,Mala
2020-07-04,4,2020,4.9,3,0.428571,96.0,958080.0,195526.530612,0.24,0.06,...,117.5,1.410002,19.591837,0.061224,0.061224,0.061224,Buena,Buena,Mala,Mala
2020-07-05,4,2020,4.9,4,0.571429,95.0,948100.0,193489.795918,0.30,0.06,...,167.5,1.215318,19.387755,0.081633,0.081633,0.081633,Buena,Buena,Mala,Mala

In [93]:
#Agupaciones
df.groupby('pool_id')['surviving'].min()
df3 = df.groupby('pool_id')[['surviving','weight(g)']].agg(['min','mean'])

In [91]:
#Peso promedio por psicina y por semana
df['weekEntera'] = df['days']//7
df2 = df.groupby(['pool_id','weekEntera'])['weight(g)'].mean()

In [96]:
df[['surviving','weight(g)','pool_id']].groupby('pool_id').agg({
    'surviving':'mean',
    'weight(g)': 'min'
})

         surviving  weight(g)
pool_id
4        81.219894       0.15
9        86.485965       0.30